In [4]:
import control as ctr

In [5]:
from control.matlab import *

In [6]:
import numpy as np


In [7]:
s = tf('s');

In [8]:
G_P=1/(s**2+1)

In [9]:
A,B,C,D=ctr.tf2ss(G_P)

TypeError: object of type 'int' has no len()

In [21]:
G_P_ss=tf2ss(G_P)
G_P_ss


StateSpace(array([[ 0., -1.],
       [ 1.,  0.]]), array([[-1.],
       [ 0.]]), array([[ 0., -1.]]), array([[0.]]))

In [57]:
A = np.array([[0,-1],[1,0]])
B = np.array([[-1],[0]])
C = np.array ([0 ,-1])
C

array([ 0, -1])

In [58]:
ctr.ctrb(A,B)


matrix([[-1.,  0.],
        [ 0., -1.]])

In [59]:
ctr.obsv(A,C)

matrix([[ 0., -1.],
        [-1.,  0.]])